public class Variables {
    public static void main(String[] args) {
        
        int age = 20;
        double salary = 25000.50;
        char grade = 'A';
        boolean isPassed = true;
        String name = "Rohan";

        System.out.println("Name: " + name);
        System.out.println("Age: " + age);
        System.out.println("Salary: " + salary);
        System.out.println("Grade: " + grade);
        System.out.println("Passed: " + isPassed);
    }
}